language: rust
rust:
- stable
install:
- rustup component add rustfmt
- rustup component add clippy
script:
- cargo fmt -- --check
- cargo clippy
services:
- docker
cache: cargo
before_deploy:
- docker build -t sns-to-slack-lambda .
- docker run -v /tmp/artifacts:/export sns-to-slack-lambda
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $BUCKET_NAME
  skip_cleanup: true
  region: eu-central-1
  local_dir: "/tmp/artifacts/"
  on:
    tags: true
