language: rust
rust:
- stable
install:
- rustup component add rustfmt
- rustup component add clippy
script:
- cargo fmt -- --check
- cargo clippy
services:
- docker
cache: cargo
before_deploy:
- docker build -t sns-to-slack-lambda .
- docker run -v /tmp/artifacts:/export sns-to-slack-lambda
deploy:
  provider: s3
  access_key_id:
    secure: jeB1mYfpT0hTAbB55vq0jtDR1lrc1M/cAMG50l2f/oucuZl3kKxygbI9OgtHSivgPBSwiaTZOdJFZyAdNC53RCKnC5lfYy2bLXhxwDAVfAzC/oOaJGSkUc5DSBtvP5DeRlKzdsE6NxYWhfCsC3iyStah8jYS5t/vaz2ufTZ1MtfDCZ3OJbvZQ4ClDAvxqp/s/LqWWoUTnHnRUbhF5tB5lT9k11dVqQrUhqu+FeAS7rfJXzLQT4yyt1F5F/8NfEtDN2KnGCh9JtPrs/Lb4nELqhfJZgX0qyDGQQ/rgmtj6rXzmM3Dyww2QeYC2RksxIDMTk3bhPI+9GzGknTJw9mN05hYVYyA/8vVN0wskvsk+4tx7CdqOyvy60ehJJkll3+nwD1HjC76gC0a/M897qmaJsGG5yKFZPE+Mea7NZnox9QecFKH+3WRUvEa1ZdjneuF02/hIz1TIKqmrKF1cIN+xiecXftnoPTie7AF7wqjdj+pfj7BWabN2jDpYdSeV+9dRd6xxsz/LHOp9Mc58GzFNlSVTt10cHmrDxRRwWMoZUK4MxXNRwGAwUegD3vKwUBqIly2evkVNN06d2GvHXIYk9w0HtVMMUJORiiYWViFBhxohS8pPZw9bV2Jw3wZwyO2B0cD5mIbjomk8lhOM+S0MNx5xUPuPXBerGFOY7rQ/eY=
  secret_access_key:
    secure: S3rI9ZhQ4S5XLrDlLeyf2Hw9HGkkIKrrhqJruhcxvdUm+G0OLiViFe4iQVcGqQT+rYoAbc82hZoFYbB6QupOKndCn1vIsX7vID45L7bko18vM0aoeK0LTe+TSJb1PQz2BoyrUzP4zps5BGI9Y1g2kMfcI45ITsJRsY9XBTX+htKw4Il3c1x/aBSwrFsZmaT2dmK31K47SKGnOQS4ADqs3ht9QV98qYep3FYuiSYLV9kzq0a9qp/ITvpOavyhJOV/fwRwDFc475uovsDs7Zg3rjoR4812tNbcvJL61eZyvMvtn3Yusl2Q99WoyJmndnj3o7O+e84w40iCxkGnwbwJY71+NcolcvvM9GXrtrYXh31Mw9FigwaK/TPxIFcAqcTTsCe/r4Ddd1tE0klastFZS+k35jxMuAbjZHI+Ji/fxkfA4tB8R6ChyjHE8S2z+k0v7ysvN89dnBh5f3NuKoR3jMdAo7Mensi3lHCEi+NqYelHuXACCTtDwficD0Sk+w/M5gcdazVDkB2hTR3VVbX1s4vn+weEuDJSGNAkKAZO1xDqbC6pu2az1dd0+a5Eb59W5/7iSiVpwtNgqkCjXGucPr9zvK7vgaBxlRdVO+VCne0xMvyFUWyeyLc7r0LV+60viW9VoUJfJh1e/LOtjsX4/kheCLMiHRXZx+dj044YuV0=
  bucket:
    secure: Wb7+6B6rrt1LgLe0LZYUZF+CbAYI5Y9xEYv3V/MBQ0ryvecgSHuobib83pXcA+JHrejdO3X9/KLH2iucPoyaMsTby+9rt+6D7WDrPwMUQd34Y68r5i73v9YuoRfDje+pC4mz7Xz56cKfnHoKLrGb+/RjChgibMDQNRGryeGQO080WLoB9l5N8uzpeq/JHZSz9J6oYirS47LeWkmIzLxlAYYWPZyAL6AWKEuMdOKrykRs13A2JV9x5Q86f6UbYrjWuGIttF+p77Ixul/mI7DXZO9UCIVi/jTSXXGXqOQK97Zqib/s91rPyE0t3kWZOy9axrlHov8y5jS/P2qt2/sGSD9ZLJRCiwfrYANTorPWituAETP00egBW6QN74UOeivVftTc4YxgZqNw2tOTd7foDxzuDbgGMhepAtrVxGW1BR7c/idxNGRc7GHhLPdTb9zE5yKOq2vvyLEO1AT7pjlr+RI9VWMEwyMy9ZKt79ECY3gqLMrOX4X1PcRifXntaRigO/S0/iSj0HxTgljswUrrvXQZBj1y2/aO5Ajll/DwUKUhP26PnSgbxzOVaC3LefcJ7AvJuZwV5B5SqhZ2iFZ7OyrkUOx8tJX8Vw0g9sUERXIlglxUlTz6otdAUhH/FcyaeYQrp6qSQHKlKX4AWOCGbh4xk1pu86Hk58fen01goAk=
  skip_cleanup: true
  region: eu-central-1
  local_dir: "/tmp/artifacts/"
  on:
    tags: true
