language: rust
rust:
- stable
install:
- rustup component add rustfmt
- rustup component add clippy
script:
- cargo fmt -- --check
- cargo clippy
services:
- docker
cache: cargo
before_deploy:
- docker build -t sns-to-slack-lambda .
- docker run -v /tmp/artifacts:/export sns-to-slack-lambda
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$BUCKET_NAME"
  skip_cleanup: true
  region: eu-central-1
  local_dir: "/tmp/artifacts/"
  on:
    tags: true
env:
  global:
  - secure: CIgGYJIiXjqkH2I2ksDc9c1JIcul+Rqopucxp2NfdB7WQuULFboQPF8uuoFuEI6HjmX0iofiSDov1o0LPiqH2rqlUMyzmg8qWQ7u5x9hsRHh54r6GuNBgRkxJ+IjJRXTtfEpURj4aqK3wmPyo3XknsOqD8vxbQqXcIZGSVo2dGDYmwESTZVKNdDILCM5XeihcSWQZXXg8j1zRaGNW3e6P2brg+yZpP1tPHrWNX4TPE2lyjgvuCiwFUsSBvOd+ssGgq07fMuab+DJKiOuRzMLQtP+TXlYJqHC6/3zwhDgMPyRiMbO1lA9jkODRpG8rMc5KK3z4fEkliLKatQ4Fa4VctszFYP4YIUSoHkPslreHeAdXvf4DpgnW9xmnnbx9q69On/1tRcw1kdNG0Stw6q3zyLrtD3adN5RKvZTsX3CL6nKkglTixNcLigKOHqDRNLdtl60CHmfV2wdGtRUfjv2zQIs4sCZ8S42iPW18+8mcySozchAY7zBzUMI6eNOmTJXjU9w4OZjIlUv/YBjEKvMc/BHMhhpfDjrhvtGhSWEEKhPWLc8RtVGZrbJAoQhDxBExRgKjrhYOEth1SCxnhCObYBdhdsSoWD8CxoZWiMpudZWWE+rrAuh58o9ZVeR0uwjybwZCVFTHJ4Dh79Gfei7eCp9EfFgHPzmSHGR3iCtXOI=
  - secure: bea8lIqRfbiuXmnaP6K/ITGGfMmiRIyzvbE5uue9XgONW36sNwAgNGP/Mad/OVD6Vlz/pam3ieGzZ2dY/ouCCu3EtzZZE5LRpk020E3XngG3/U7uDMJIDc15jo5AyDiPOTk0XDhVNZCDXH4v6c4VtZxv0bv+oLm3fLvvPuLi+zasg8+kTqGAlqQmyFnMvdNJ2R7QaKMtV2uL5UKWLqaXLuLxk2hzQyTG+HsT8UaVMGMiY/gAe0g91eEqaGSYnqGKx5BRZVuIgH4bFFloI9otiji4shOmIuSHm/RONg4HgIU5JgIxQtG4FGXY/Og89Gz3NOMUIvcymn5nEHG3rLOpNmvFjWXy+fB23cIKApucB3mu4OeKy1JDaAkTGMsRxdszX8CWciwZWybtp48/2wfQ2CfUdHrIMBvcdfngcbPYGZkURPSlsdyai9nKbnVIYyMoLkxgWM5Oe33JCHRlnXB1KGwokxFuuEAcusXQRwvIS84hMrriIl45IgFRzfVxkrtWXX422PqdeVgu9xZJ6pJzKwPfBb3qTu67aeE2vd3A+nD3uqavdbNnbfNAeYLhnxE2Jh9FDlNeQr/7DkRDDdzEyUiNd3Ll+q9bJBLGtxivCarPFr/awLhqjgEAHHdXRbslcPzuVgHKCW22zOnxRHw+JXzmlMvsa36GPrGJjdE8VvQ=
  - secure: bloisL2er0Xr8oB/RXGTSKQPsjvAV/RKJ+8/kaVXRDusPcfE4IGSG7NJ+vlrcupx8jXxhhcmEzwWLbQ7tCinb9yhp98ZXkDReQQddYJPlj3DcQ736+EEZYMqKUxAPKHtEUda4vNM8M7/pVtZ+QuK3mhx/lhMHfeC9l3ekd9VRWqDMTQAx/KAhSIVl4Y6dBIpR/iwS57ZSkXsz2Vsqr7dGhqX3jT0SIrd7JCGHGszscd8ZJJ618t6+Ew8JZ4XhSe80/PsyYUT3U2FPp3l1dxttVY0dqiO20S417kxTtd1ioae7KKTNxK6Jc7keYoTPVfvIgoy4kR+n4wDyaXhfAASAMtyOjg4HflorHZYkvbUOFEae6jZ5KXC90MOkQBZjZEl4GIEiPLB8EQtIHLiVmjpzIBDya3BbE4HZnBohUQqyx56SNfMooWhAyBHLBcgE48OY+m1Kvh/5TqHtDOm0El50oP+lVwewlTcvd48g9aQ1ipcA2hjYZVdBZrDG9ReXjuOpCH2DtxfkZPuinWUsduSWW3gQS8a8xG3GwIku5FeVEtUr19fEJfM9E5YlCqVCxI1guOtwC70AxFWdm/Dp7fq0458bvPBZw+0UZapkNAEhuxSuIFZYguica6Mz5AGikQyoNYh1+8ut/REDJNp80gQQ3e0FYZKJBz1YKte/pYg/O8=
