[package]
name = "sns-to-slack-lambda"
version = "0.1.0"
authors = ["snowiow <marcel.patzwahl+github@posteo.de>"]
edition = "2018"

[dependencies]
lambda_runtime = "0.2.0"
aws_lambda_events = "0.2.1"
slack-hook = "0.8.0"
dotenv = "0.13.0"
