only-deploy-tags: &only-deploy-tags
  filters:
    tags:
      only: /^v\d+\.\d+\.\d+/
    branches:
      ignore: /.*/

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.9
jobs:
  test:
    docker:
      - image: softprops/lambda-rust
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name:    Source PATHs
          command: |
            echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
      - run:
          name:    Versionen
          command: |
            rustc -V
            cargo --version
      - run:
          name:    Check Code
          command: |
            cargo check --color=always --locked
      - run:
          name:    Check Format
          command: |
            rustup component add rustfmt
            cargo fmt -- --check
      - run:
          name:    Check Clippy
          command: |
            rustup component add clippy
            cargo clippy --all -- --check
      - run:
          name:    Test
          command: |
            cargo test --verbose -- --nocapture
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
  deploy:
    docker:
      - image: softprops/lambda-rust
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Build with Lambda Docker Container
          command: |
            /usr/local/bin/build.sh
      - aws-s3/copy:
          from: target/lambda/release/cloudwatch-to-slack-lambda.zip
          to: "s3://$BUCKET"
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
workflows:
  version: 2
  test:
    jobs:
      - test
  test_and_deploy:
    jobs:
      - test: *only-deploy-tags
      - deploy:
          <<: *only-deploy-tags
          requires:
            - test

